### ISSUE TITLE
"Forgot Password" service needed !!!

### ISSUE THREAD

**Issue by d0rg0ld** [DM2E/dm2e-gui#19]

**Comment by kba** [comment]
The user management is handled by MPIWG's Josso gateway, not dm2e-ws.

**Comment by jurzua** [comment]
This issue has been settled.
In order to be able to reset the password, it is necessary to have an email for each user. For this reason, I decided that username must always be an email.

Currently, there are many accounts, whose username is not an email. 
For these accounts, the password reset does not work; therefore they will be removed on September 30. 

If your username is not an email, please create a new account.

**Comment by d0rg0ld** [comment]
Ok, I understand, thanks!
