### ISSUE TITLE
Improve usability of file selection in "Create Config" page

### ISSUE THREAD

**Issue by d0rg0ld** [DM2E/dm2e-gui#24]
This is not very usable, I have to write down the key of each item in order to find it in the list. At least you could try to filter all items by the currently logged in user. better: show key, creator and FILENAME!!!

There is no visual feedback when someone drags an ID from the list to its respective field. Only when the mouse is over the field, you get visual feedback, before its a blind run.

The list is way to long, one must be able to filter the list and to scroll through it !!!

**Comment by kba** [comment]
Was fixed in https://github.com/DM2E/dm2e-gui/commit/fc9372f390ae6a99fa1f5da6b6d3ba0183d1c08d, the list shows the label now (not yet deployed). The filtering functionality is on my TODO, was in the prototype. But it's hard to stuff all the information into essentially a bullet point in a list and keep it manageable at the same time.

**Comment by kba** [comment]
The file list in the config editor is now a vertical tab bar style interface with limited height (scrolling). Individual files consist of two lines each, containing the filename, the filetype, the upload date and the owner.

As soon as you start dragging files to the parameters, their background is slightly highlighted.

The filtering is more work and I opened a new issue (#29)
