### ISSUE TITLE
Multiple workflow parameters and other connections can be created from one input param?

### ISSUE THREAD

**Issue by kaiec** [DM2E/dm2e-gui#3]
You can add an input parameter several times, with the same label or with different labels, they all get connected to the same input parameter. Probably this should be prevented.

**Comment by kba** [comment]
The straight-forward approach would be to mark connected parameters in the position list and prevent them from being dragged. Will be tricky to get the wiring right though (detect on-the-fly that a parameter in a webservice in a position is to be marked because a connector links to this param) and to keep it synchronized.

Another solution would be to use the validate service method in workflowservice to detect whether there are errors (unconnected required params or invalid connectors) or warnings (multiple connectors pointing to the same param  or unconnected positions). Correctly mapping the server response to backbone models/views will be even trickier.
